spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

server:
  port: ${SERVER_PORT}

# Optional: logging
logging:
  level:
    org.springframework: INFO
jwt:
  secret: ${JWT_SIGNED_KEY}
  expiration: 86400000 # 1 ngày